# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dash-migrationLTE-v2', ['esba-dash-energy', 'internet', 'wifi', 'buildings', 'applications', 'point-to-point','internet-apps','lte'])
    obj.source = 'dash-migrationLTE-v2.cc'
